import { Movie, Genre } from './types';

export const QARAQALPAQFILM_LOGO = "https://files.catbox.moe/m6dx8r.png";
export const QMU_LOGO = "https://files.catbox.moe/fyv35n.png";
export const UNI_ACADEMY_LOGO = "https://files.catbox.moe/d04yo3.png";

export const GENRES: Genre[] = [
  { id: 'comedy', label: 'Komediya' },
  { id: 'drama', label: 'Drama' },
  { id: 'action', label: 'Urıs-talas' },
  { id: 'horror', label: 'Qorqınıshlı' },
  { id: 'adventure', label: 'Sargúzash' },
  { id: 'animation', label: 'Multfilm' },
  { id: 'qaraqalpaq', label: 'Qaraqalpaq Film' },
  { id: 'history', label: 'Tariyxıy' }
];

export const MOCK_MOVIES: Movie[] = [
  {
    id: 116,
    title: "Afsonalar jangi",
    year: 2024,
    rating: 9.0,
    quality: "Full HD",
    genre: ["Urıs-talas", "Sargúzash"],
    imageUrl: "https://files.catbox.moe/m6dx8r.png",
    videoUrl: "secure://movie/116",
    description: "Afsonalar arasındaǵı qızıqlı hám kúshli qarama-qarsılıq waqıyası.",
    duration: "1s 30m",
    country: "Qaraqalpaqstan",
    isQaraqalpaq: true,
    director: "Kino TAP",
    actors: ["Bas qaharmanlar"]
  },
  {
    id: 115,
    title: "Jańa jıl sawġası",
    year: 2024,
    rating: 9.5,
    quality: "Full HD",
    genre: ["Sargúzash", "Qaraqalpaq Film"],
    imageUrl: "https://img.youtube.com/vi/tUz1HmWREAk/hq720.jpg",
    videoUrl: "secure://movie/115",
    description: "Jańa jıl bayramı qarsańındaǵı kútilmegen sawǵalar hám ájayıp mo'jizalar haqqındaǵı bayram kinosı. Shańaraq penen kóriw ushın eń jaqsı tańlaw.",
    duration: "1s 15m",
    country: "Qaraqalpaqstan",
    isQaraqalpaq: true,
    director: "Qaraqalpaqfilm",
    actors: ["Zamanagóy Aktyorlar"]
  },
  {
    id: 114,
    title: "Qaysar (kórkem film)",
    year: 2024,
    rating: 9.6,
    quality: "4K UHD",
    genre: ["Drama", "Urıs-talas", "Qaraqalpaq Film"],
    imageUrl: "https://img.youtube.com/vi/w_LypPgbUkI/hq720.jpg",
    videoUrl: "secure://movie/114",
    description: "Qaysar waqıyasınıń kórkem film variantı. Qaraqalpaq jigitiniń mınásip ómiri hám qıyınshılıqlarǵa qarsı gúresi haqqındaǵı tásirli kórkem film.",
    duration: "1s 40m",
    country: "Qaraqalpaqstan",
    isQaraqalpaq: true,
    director: "Qaraqalpaqfilm",
    actors: ["Jas Aktyorlar"]
  },
  {
    id: 113,
    title: "Qaysar 1-bólim",
    year: 2024,
    rating: 9.2,
    quality: "Full HD",
    genre: ["Drama", "Qaraqalpaq Film"],
    imageUrl: "https://img.youtube.com/vi/JJQBeKviYX0/hq720.jpg",
    videoUrl: "secure://movie/113",
    description: "Qaysar serialınıń birinshi bólimi. Qaharmanımızdıń qıyınshılıqlarǵa tolı jolı baslanadı. Waqıyalar qalay rawajlanadı?",
    duration: "55m",
    country: "Qaraqalpaqstan",
    isQaraqalpaq: true,
    director: "Qaraqalpaqfilm",
    actors: ["Kino Aktyorları"]
  },
  {
    id: 112,
    title: "Yapırmay",
    year: 2023,
    rating: 9.4,
    quality: "Full HD",
    genre: ["Komediya", "Qaraqalpaq Film"],
    imageUrl: "https://img.youtube.com/vi/I7Wz75S6CPU/hq720.jpg",
    videoUrl: "secure://movie/112",
    description: "Kúlkili waqıyalar hám kútilmegen jaǵdaylarǵa tolı qızıqlı komediya filmi. Zamanagóy Qaraqalpaq kúlkisinen bahra alıń.",
    duration: "1s 20m",
    country: "Qaraqalpaqstan",
    isQaraqalpaq: true,
    director: "Qaraqalpaqfilm",
    actors: ["Komediya Ustaları"]
  },
  {
    id: 111,
    title: "Civilizaciya",
    year: 2024,
    rating: 9.1,
    quality: "4K UHD",
    genre: ["Drama", "Qaraqalpaq Film"],
    imageUrl: "https://img.youtube.com/vi/tY9NtRtUm6I/hq720.jpg",
    videoUrl: "secure://movie/111",
    description: "Insanıylıq hám zamanagóy jámiyet munasábetleri haqqındaǵı tereń mazmunlı Qaraqalpaq kinosı. Civilizaciyanıń keri tárepleri hám insaniy qádiriyatlar.",
    duration: "1s 30m",
    country: "Qaraqalpaqstan",
    isQaraqalpaq: true,
    director: "Qaraqalpaqfilm",
    actors: ["Professional Teatr Aktyorları"]
  },
  {
    id: 110,
    title: "5 bala",
    year: 2024,
    rating: 9.5,
    quality: "Full HD",
    genre: ["Komediya", "Qaraqalpaq Film"],
    imageUrl: "https://img.youtube.com/vi/dfuaQFaTtjg/hq720.jpg",
    videoUrl: "secure://movie/110", 
    description: "Bes balanıń qızıqlı hám sargúzashlarǵa tolı waqıyaları haqqındaǵı jańa Qaraqalpaq kinosı. Shańaraq penen kórıwge mınásip komediya.",
    duration: "1s 20m",
    country: "Qaraqalpaqstan",
    isQaraqalpaq: true,
    director: "Qaraqalpaqfilm",
    actors: ["Zamanagóy Aktyorlar"]
  },
  {
    id: 109,
    title: "Kvartirantlar 6-bólim",
    year: 2024,
    rating: 9.7,
    quality: "4K UHD",
    genre: ["Komediya", "Qaraqalpaq Film"],
    imageUrl: "https://img.youtube.com/vi/4-7PsgFmF0E/hq720.jpg",
    videoUrl: "secure://movie/109", 
    description: "Kvartirantlar serialınıń altınshı bóliminde qaharmanlardıń qaladaǵı qızıqlı sargúzashları dawam etedi. Jańa kúlkili waqıyalar hám kútilmegen burılıslar! Barlıq kúlkili waqıyalar tikeley saytta!",
    duration: "1s 10m",
    country: "Qaraqalpaqstan",
    isQaraqalpaq: true,
    director: "Qaraqalpaqfilm",
    actors: ["Zamanagóy Komediya Ustaları"]
  },
  {
    id: 108,
    title: "Kvartirantlar 1-bólim",
    year: 2024,
    rating: 9.6,
    quality: "4K UHD",
    genre: ["Komediya", "Qaraqalpaq Film"],
    imageUrl: "https://img.youtube.com/vi/IJptQk6RLcM/hq720.jpg",
    videoUrl: "secure://movie/108", 
    description: "Qaraqalpaqstanlı jaslardıń qaladaǵı kvartiradaǵı qızıqlı hám kúlkili waqıyaları haqqındaǵı jańa komediya. Filmnin birinshi bóliminde qaharmanlardıń tanısıwı hám kútilmegen sargúzashları sheberlik penen súwretlengen.",
    duration: "1s 15m",
    country: "Qaraqalpaqstan",
    isQaraqalpaq: true,
    director: "Qaraqalpaqfilm",
    actors: ["Zamanagóy Komediya Ustaları"]
  },
  {
    id: 107,
    title: "Ájiniyaz",
    year: 2024,
    rating: 9.8,
    quality: "4K UHD",
    genre: ["Tariyxıy", "Drama", "Qaraqalpaq Film"],
    imageUrl: "https://img.youtube.com/vi/yvNojewLPLc/hq720.jpg",
    videoUrl: "secure://movie/107", 
    description: "Ullı Qaraqalpaq shayırı Ájiniyaz Qosıbay ulı ómirine baǵıshlanǵan eń jańa tariyxıy kórkem film. Milliy maqtanıshımız tikeley efirde.",
    duration: "2s 10m",
    country: "Qaraqalpaqstan",
    isQaraqalpaq: true,
    director: "Qaraqalpaqfilm",
    actors: ["Professional Teatr Aktyorları"]
  },
  {
    id: 106,
    title: "Kúydirgi",
    year: 2024,
    rating: 9.3,
    quality: "4K UHD",
    genre: ["Komediya", "Qaraqalpaq Film"],
    imageUrl: "https://img.youtube.com/vi/KpT9rp1zdV0/hq720.jpg",
    videoUrl: "secure://movie/106", 
    description: "Qaraqalpaq komediya janrındaǵı eń jańa hám kúlkili filmlerden biri. Sayttan shıqpastaq kórıw múmkinshiligi.",
    duration: "1s 25m",
    country: "Qaraqalpaqstan",
    isQaraqalpaq: true,
    director: "Qaraqalpaqfilm",
    actors: ["Komediya Aktyorları"]
  }
];
